name: Code Climate coverage report

on:
  push:
    branches:
      - main

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Install Dependencies
        run: go get ./...
      - name: Report Coverage
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageCommand: go test -coverprofile=c.out ./...
          debug: true
          prefix: ""