name: Code Climate coverage report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files
        run: ls -R
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Install Dependencies
        run: |
          go mod tidy
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Report Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -coverprofile=c.out ./...
          debug: true
          prefix: ${{ github.workspace }}